import { AuthProvider } from '@/contexts/auth-context';
import { Toaster } from 'sonner';
import NotificationProvider from '@/components/NotificationProvider'; // 👈 Imported here

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {/* 💡 Connects the real-time notification layer over all internal paths */}
          <NotificationProvider>
            {children}
          </NotificationProvider>
        </AuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}